# Generated by Django 2.1.2 on 2018-11-05 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 14, 19, 38, 101412), verbose_name='添加时间'),
        ),
    ]
