# Generated by Django 2.1.2 on 2018-10-27 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 18, 51, 1, 824012), verbose_name='添加时间'),
        ),
    ]
