# Generated by Django 2.1.7 on 2019-04-30 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190227_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 17, 5, 27, 754719), verbose_name='添加时间'),
        ),
    ]
