# Generated by Django 2.1.7 on 2019-04-30 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190430_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 17, 14, 33, 116037), verbose_name='添加时间'),
        ),
    ]
